### ISSUE TITLE
Hits sometimes cause segfaults?

### ISSUE THREAD

**Issue by zbanks** [ervanalb/beat-off#17]
Really hard to reproduce. 

Also sometimes solid hits don't remove themselves.

-Zach

**Comment by zbanks** [comment]
Steps to reproduce:
- Hook up light strips so the output code fires -- causing the hits to get updated in two separate threads
- Add just a few hits

``struct active_hit`` needs some type of locking system to get removed. Probably only ``.update`` should be able to remove the hit.

**Comment by ervanalb** [comment]
I think we need to do a thorough review of the threading and come up with a good locking strategy

**Comment by zbanks** [comment]
Hits are killed
